title: Priya Sara George # your name (or website title) here
logo: "/images/oooo.plus_188.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
A highly motivated and results-driven professional with six years of experience in software development, testing, and project
management. Currently pursuing my Master of Science with a focus on artificial intelligence and big data, I am passionate about leveraging
cutting-edge technologies to solve complex business challenges. My technical expertise includes advanced proficiency in Python, R, Excel,
Power BI, PyTorch, Deep Learning, SQL, Machine Learning, Computer Vision, and Cloud Computing. 
  <br><br>
  I have successfully delivered several software solutions, including web and mobile applications using Angular, React, TypeScript, and JavaScript. In addition, I have conducted
research in the area of Japanese e-commerce websites, resulting in several successful product launches. As a proactive and collaborative team
player, I have worked closely with developers, project managers, business analysts, product consultants, and test teams using the Agile
Scrum methodology. I am now looking for a challenging role in artificial intelligence and research areas where I can utilize my technical, self-
management, analytical, and teamwork skills to drive innovation and contribute to organizational success.
  <br><br>
  <a href="https://www.linkedin.com/in/priyasarageorge/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
