title: Priya Sara George # your name (or website title) here
logo: "/images/oooo.plus_188.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Motivated software professional with 6 years in development, now holding an MSc in AI and Big Data. Proficient in Python, R, Power BI,
  Deep Learning, SQL, Cloud Computing, and Computer Vision seeking an impactful role in Data Science and AI.
  <br>
  <a href="https://www.linkedin.com/in/priyasarageorge/">View my LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
